version: 0.0
os: linux
files:
  - source: ctk-qa1/build-output.zip
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  ApplicationStart:
    - location: scripts/start_server.sh
